spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 08203
      url: jdbc:postgresql://localhost:5432/ted

  profiles:
      active: prod


uploads:
   folder: D:/images/


---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 9090